baseURL = "https://anton.tools"
theme = "risotto"
title = "tonindexer"
author = "datboi"
copyright = "© 2022–2023 [Dat Boi](https://datboi420.t.me)."
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true

# Automatically add content sections to main menu
sectionPagesMenu = "main"

[params]
noindex = false

[params.theme]
palette = "base16-dark"

[params.about]
title = "tonindexer"
description = "The project to index data from TON blockchain."
logo = "images/database-solid.svg"

[[params.socialLinks]]
icon = "fa-solid fa-infinity"
title = "Apache Superset"
url = "https://superset.anton.tools/dashboard/list"

[[params.socialLinks]]
icon = "fa-solid fa-code"
title = "API docs"
url = "https://anton.tools/api/v0/swagger"

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/tonindexer"

[[params.socialLinks]]
icon = "fa-brands fa-telegram"
title = "GitHub"
url = "https://t.me/tonindexer"

[[params.socialLinks]]
icon = "fa-solid fa-envelope"
title = "Email"
url = "mailto:datboi@anton.tools"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
